sudo: false
language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 'stable'
  - '9'
  - '8'
  - '6'
  - '5'

env:
  CODECLIMATE_REPO_TOKEN: 4bf8e178d6768b6bf836f766d2d10c6fa7c71a22448e10c464d3c29b240bcef6

script:
  - npm run build
  - npm test

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

jobs:
  include:
    - stage: release
      node_js: '9'
      script:
        - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
