sudo: false
language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - 'stable'

before_script:
  - npm prune
  - npm install -g gulp
  - npm install -g typings
  - typings install

after_script:
  - npm run-script send-coverage

after_success:
  - npm run semantic-release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
